version = 2

songs = "*.md"

notation = "german"

[[output]]
file = "songbook.pdf"

[[output]]
file = "songbook.html"

[book]
title = "Střediskový zpěvník"
subtitle = "beta - Tábor 2026"
chorus_label = "R"
title_note = "2026"
